---
title: "plotly"
author: "Jiayi Yang"
date: "2022-10-25"
output: html_document
---

## Load packages and data
```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```
Let's get some data
```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2 ) %>% 
  select(
    borough = neighbourhood_group, neighbourhood, rating, price, room_type, lat, long
  ) %>% 
  filter(
    !is.na(rating),
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  )
```
```{r}
nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)

```

## Bar plot
```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

## create a dashboard
```{r}

```

